package jpapersistence;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.time.LocalDate;
//import java.util.Calendar;
import java.util.UUID;

@Entity
@Table(name = "team", schema="public", catalog="cctest")
public class Team implements Cloneable {
    // @Id
    // @GeneratedValue(strategy = GenerationType.IDENTITY)
    // private Integer id;

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(unique = true)
    private String name;

    @Column(name = "date_est")
    //@Temporal(TemporalType.DATE)
    //private Calendar dateEst;
    private LocalDate established;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // public Calendar getDateEst() {
    //     return dateEst;
    // }

    // public void setDateEst(Calendar dateEst) {
    //     this.dateEst = dateEst;
    // }


    public LocalDate getEstablished() {
        return established;
    }

    public void setEstablished(LocalDate established) {
        this.established = established;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}

/*
@GeneratedValue(strategy = GenerationType.IDENTITY)
create table public.team (
       id int4 generated by default as identity,
        name varchar(255),
        primary key (id)
    )

 */
